### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by zanehmw** [ga-dc/wdi9-project1-gallery#10]
For my deck of cards I have created multiple objects within an array (displayed below). I would like to create a function of some sorts to display some of the information within the arrays on my page. However , I cannot access the information within the object. How can I zero in on one property within these objects?

var deck = [
  { cardPosition: "1",
    eWord: "Hello",
    kWord: "안녕하세요",
    answered: false,
    correct: false,
  },
  {
    cardPosition: "2",
    eWord: "excited",
    kWord: "신났다",
    answered: false,
    correct: false,
  },
  {
    cardPosition: "3",
    eWord: "What is your name?",
    kWord: "이름이 뭐예요?",
    answered: false,
    correct: false,
  },
];

**Comment by tylercrosse** [comment]
Hey Zaneh, can you resubmit this issue on https://github.com/ga-wdi-exercises/project1. I'd be happy to continue this conversation there!
